### ISSUE TITLE
Configuration Keys

### ISSUE THREAD

**Issue by johan-developer** [IEvangelist/signalr-chat#4]
Hello,

When I runned the first time, have this error:
![image](https://user-images.githubusercontent.com/83321972/156651300-35fb66bc-55c9-4a92-93f7-cf86de3e2deb.png)

This configuration it's in appsettings.json and wich api you used to do that Microsoft or Google?

**Comment by IEvangelist** [comment]
Hi @johan-developer,

To run locally, you'll need to have several environment variables created. The `configuration` object is expecting a value that doesn't exist. For the translator specifically, you'll need to create an Azure account, and corresponding Azure resource for the translator. There is a free tier, you can sign up here:

https://docs.microsoft.com/azure/cognitive-services/translator/translator-how-to-signup?wt.mc_id=dapine

#### Environment Variables

| Name | Value |
|------|-------|
| `TranslateTextOptions__ApiKey` | <Your Translator Resource's API key> |
| `TranslateTextOptions__Endpoint` | `https://api.cognitive.microsofttranslator.com/` |
| `TranslateTextOptions__Region` | <Your Translator Resource's Region> |

> After you've created the resource, and added the environment variables, close and reopen your IDE. It should then work.

**Comment by johan-developer** [comment]
Thank you so much David.
